package com.example.footballtracker.data.local.dao

import androidx.room.*
import com.example.footballtracker.data.local.entity.MatchEntity
import com.example.footballtracker.data.local.entity.PlayerEntity
import com.example.footballtracker.data.local.entity.MatchWithPlayers
import kotlinx.coroutines.flow.Flow

@Dao
interface MatchDao {

    // -------------------
    // MATCHES
    // -------------------

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertMatch(match: MatchEntity): Long
    // Returns the autogenerated matchId

    @Query("SELECT * FROM matches ORDER BY timestamp DESC")
    fun getAllMatches(): Flow<List<MatchEntity>>

    // -------------------
    // PLAYERS
    // -------------------

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlayers(players: List<PlayerEntity>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertPlayer(player: PlayerEntity): Long

    @Query("SELECT * FROM players WHERE matchOwnerId = :matchId")
    suspend fun getPlayersForMatch(matchId: Long): List<PlayerEntity>

    @Query("SELECT * FROM players")
    fun getAllPlayers(): Flow<List<PlayerEntity>>

    // -------------------
    // MATCH WITH PLAYERS (RELATION)
    // -------------------

    @Transaction
    @Query("SELECT * FROM matches ORDER BY timestamp DESC")
    fun getMatchesWithPlayers(): Flow<List<MatchWithPlayers>>
}